name: Pipeline CI/CD

on:
  push:
    branches:
      - main

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Installation et Test Backend
        working-directory: ./backend
        run: |
          npm install
          npm test

      - name: Connexion DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build et Push Backend
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          push: true
          tags: marinecdt/backend:latest

      - name: Build et Push Frontend
        uses: docker/build-push-action@v4
        with:
          context: ./frontend
          push: true
          tags: marinecdt/frontend:latest

  deploy:
    needs: test-and-build
    runs-on: ubuntu-latest
    steps:
      - name: Déploiement sur la VM Azure
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VM_IP }}
          username: ${{ secrets.VM_USER }}
          password: ${{ secrets.VM_PASSWORD }}
          script: |
            # Mise à jour des images dans le cluster
            kubectl rollout restart deployment/backend
            kubectl rollout restart deployment/frontend
            kubectl rollout restart deployment/db